matches:
  - trigger: ";fhcpp"
    replace: |
              /*

              ============
              Created: {{mydate}}

              Copyright 
              Mohammad Yasir
              Research Scholar, IIT-D

              All rights reserved. No part of this code may be used, modified, shared, or reproduced in any form without express permission of its author.

              DESCRIPTION
              -----------

              */
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"


  - trigger: ";fhp"
    replace: |
              '''

              ============
              Created: {{mydate}}

              Copyright 
              Mohammad Yasir
              Research Scholar, IIT-D

              All rights reserved. No part of this code may be used, modified, shared, or reproduced in any form without express permission of its author.

              DESCRIPTION
              -----------

              '''
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"


# Matplotlib
  - trigger: ";mplib"
    replace: "import matplotlib.pyplot as plt"

  # Simple plot
  - trigger: ";plot"
    replace: "plt.plot($|$)"

  # Scatter plot
  - trigger: ";scatter"
    replace: "plt.scatter($|$)"

  # Stem plot
  - trigger: ";stem"
    replace: "plt.stem($|$)"

  # Gird, legend, show
  - trigger: ";showfull"
    replace: |
              plt.legend()
              plt.grid()
              plt.show()

  # Legend, show
  - trigger: ";showleg"
    replace: |
              plt.legend()
              plt.show()

# numpy
  - trigger: ";numpy"
    replace: "from numpy import *   #type: ignore"
